### ISSUE TITLE
Enable dashboard through regular OAuth credentials

### ISSUE THREAD

**Issue by gberche-orange** [Orange-OpenSource/autosleep#101]
The dashboard current requires admin secret as basic auth, and then can't be used by cf users which authenticate through Oauth SSO.

@s-bortolussi might help if needed (see [sandbox-ui](https://github.com/Orange-OpenSource/elpaaso-sandbox-ui/blob/master/src/main/java/com/orange/clara/cloud/services/sandbox/ui/config/SecurityConfiguration.java#L98-L126) as an example)

Alternatively, temporary remove the dashboard url to avoid confusing CF users

**Comment by antechrestos** [comment]
So far disabling authentication seems ok.
