### ISSUE TITLE
Start of application is low...Sometime

### ISSUE THREAD

**Issue by antechrestos** [Orange-OpenSource/autosleep#134]
The very first sql call (get connection?) from application may be very long (around 5 minutes in my case).

Therefore, if this first sql call is in an operation context, caller timeout is reached before the creation of the schemas is completed...Leading to a non responding application since schemas creation is aborted/interrupted.

The schemas creation/update shall be done from application listener

Use actuator `/health` or `/dump` to diagnose

**Comment by arnaudruffin** [comment]
Enable to reproduce it for now...
I've just added the actuator, so that we can use `/health` `/dump` next time it occurs.
