### ISSUE TITLE
Documentation update for idle-duration configuration parameter

### ISSUE THREAD

**Issue by PadmaB** [Orange-OpenSource/autosleep#174]
Hi,

Minor correction required for the documentation.
The parameter in the below example should be 'idle-duration' instead of inactivity

> Example:'{"**inactivity**": "PT1H15M"}' would stop the application after 1 hour and 15 minutes of inactivity.

Thanks,
Padma

**Comment by antechrestos** [comment]
@PadmaB Thanks I will handle it
