### ISSUE TITLE
Web archive (war) file unavailable for release 0.2.2

### ISSUE THREAD

**Issue by pradyutsarma** [Orange-OpenSource/autosleep#176]
Hi,

The war file for pre-release 0.2.2 is not available within the downloads section of the release, whereas the same is available for other releases. On the other hand, there is a jar available for this release. Don't know why? 
Can we have the war uploaded for this release (0.2.2) too? or is there a release planned with the latest commits/fixes?

Best Regards,
Pradyut.

**Comment by antechrestos** [comment]
Hey,

Thanks for your feedback, looks like I may have a need for glasses :smile: 

Best Regards,

Ben

**Comment by pradyutsarma** [comment]
@antechrestos Thanks for the build. Do you plan to do a release for the last couple of bug fixes that have gone in?

**Comment by arnaudruffin** [comment]
Hi! I think we will release a new version before the end of the month. In the meantime, if you want to test you can still build the project using [the documentation](https://github.com/Orange-OpenSource/autosleep/blob/develop/doc/build.md).
