### ISSUE TITLE
Service enabled for other orgs fails to stop the applications after the idle-duration

### ISSUE THREAD

**Issue by PadmaB** [Orange-OpenSource/autosleep#179]
Hi,

Below is the setup in my local installation:
1. I have deployed the '_autosleep_' application in the my '_master_' org and '_prod_' space 
2. I have registered the service-broker and enabled the access to another org, say '_custom_' using the cli command '_cf enable-service-access ..._'
3. With this I can see the autosleep service in the '_custom_' org. 
4. I have now created an instance in one of the spaces, say, '_dev_' in the '_custom_' org
5. I have some apps deployed in the '_dev_' space. However, they don't seem to get bound to the autosleep service instance, even after the defined idle-duration

Is this a known issue? My understanding is, normally this will be the standard setup for '_autosleep_' service. 

Thanks and Kind Regards,
Padma

**Comment by gberche-orange** [comment]
Hi @PadmaB 

I confirm your expected behavior documented and tested at https://github.com/Orange-OpenSource/autosleep/blob/develop/acceptance/4_application_autobind.robot#L13-L20

Which version of the autosleep service are you using ?
Can you please check the autosleep app logs, especially for failures to connect to the cloudfoundry API as reported in #171 

If you try against the latest head on the "develop" branch, the failure should prevent the autosleep at start.

**Comment by PadmaB** [comment]
Hi,

Sorry for the delay on this!
I think I understand what is the issue here, the user [cf.client.username] that is used while provisioning the service is not the SpaceDeveloper where the above raised issue has popped up.
How is this expected to work?
Normally the service is provisioned [deployed] is some 'central org' and then the service access is enabled for all the organizations which would need autosleep functionality. In such a scenario, it is unlikely that the user [cf.client.username] will have SpaceDeveloper role in every org/space where the service is enabled. Also, there could arise security concerns.
Is there any alternative approach to this?
What are your thoughts on this?

Thanks and Kind Regards,
Padma

**Comment by gberche-orange** [comment]
@PadmaB 

Currently, the prerequisite CC API account either: 
   1- needs to be a space developer for each managed space as documented onto https://github.com/Orange-OpenSource/autosleep/blob/develop/doc/publish.md#prepare-your-manifest in the prereq "a CC API user with cloudcontroller.read and cloudcontroller.write scopes, and role "SpaceDevelopper" on the enrolleable autosleep spaces" part.
   2-  needs to have `cloudcontroller.admin` scope

We are considering future support for an admin to specify a set of spaces to be managed within an organization, or a set of organizations within a CF instance. As part of this feature, it could be envisaged to require the CC API account to have OrgManager role on each of the managed role, and use this to dynamically add itself as space developer on each of the managed space (as the CLI is curently doing when creating a space). 

Until then, the recommended usage is to script the autosleep service instance creation in spaces, along with adding space developper membership to the CC API account provided to autosleep app.

With respect to security impact of having an autosleep CC API account be given space developer role on each managed space, I had suggested the related [Service Broker User delegation during provisionning](https://docs.google.com/document/d/1DoAbJa_YiGIJbOZ_zPzakh7sc4TB9Tmadq41cfSX0dw/edit?usp=sharing) which I encourage you to read and comment.

BTW, are you attending the cf summit next week ? Would be great to exchange more together on the use-cases you see for autosleep.

**Comment by PadmaB** [comment]
@gberche-orange 
Unfortunately, I am not attending CF Summit but I will interested to know the roadmap for autosleep, especially the autowakeup feature that is under implementation. It is very interesting and will make the autosleep solution more complete.

Thanks for sharing the above details, will go through the details and revert back for further queries/feedback.

Thanks,
Padma

**Comment by gberche-orange** [comment]
closing in favor of #201 

Please reopen/comment if I missed something
