### ISSUE TITLE
ServiceId and PlanId instead of their names accepted as env parameters in Manifest ??

### ISSUE THREAD

**Issue by pradyutsarma** [Orange-OpenSource/autosleep#181]
Cloudfoundry recommends that service ids and plan ids should be UUIDs to maintain uniqueness across the CF system. However, in this case, the ids are accepted via the manifest env parameters.
Also, the ids are also used as the display names of the service and the plan. 

It would be nice if we could have generated UUIDs for the IDs and the service and plan names (that appear in the display) could be provided via the manifest instead.

Maybe, the catalog could itself be exposed as a json or yml file (ignoring the operational aspects of it like unchecked plans etc)

**Comment by gberche-orange** [comment]
thanks @pradyutsarma for your suggestion. Indeed this is one aspect we haven't brought much attention yet. The current impact is that it is not possible to deploy two autosleep brokers instance in the same CF instance with same service and plan names (e.g. configured with different credentials, and published in different organisation)

What about rewording this as:
- support configuring service name independently of broker id currently configured by `cf.service.broker.id` and used as UIID)
- support configuring plan name independently of broker id currently configured by `cf.service.plan.id` and used as UIID)

**Comment by pradyutsarma** [comment]
What I understand is that, the service and plan names will also be available as independent parameters in the manifest and the ids being generated as UUIDs. That's fine by me.

Maybe you can also add description to the configurable list as well :)

**Comment by gberche-orange** [comment]
Would be interesting to see if a fix for https://github.com/spring-cloud/spring-cloud-cloudfoundry-service-broker/issues/11 could help making some fields configureable by default through env vars, while having others controlled to add configureable by the autosleep code.

**Comment by pradyutsarma** [comment]
:+1:
