### ISSUE TITLE
Dashboard app state wording

### ISSUE THREAD

**Issue by gberche-orange** [Orange-OpenSource/autosleep#191]
The dashboard currently displays the app state with `watched`, and `ignored` values.

It would be interesting to consider rewording into "enrolled" and "opted-out" values instead to be consistent with the naming proposed in the params.

**Comment by arnaudruffin** [comment]
It should be ok on `feature-wildcard-proxy` branch

**Comment by PadmaB** [comment]
Hi,
I am interested to check out the dashboard for the autosleep service. How can I access the same? Couldn't find any documentation on this, any pointer would help.
Thanks,
Padma

**Comment by arnaudruffin** [comment]
Hi!

Cloud Foundry allows services to provide "dashboards" for each service instance, providing access to administrative features.

Users can retrieve their dashboard URL when creating a service instance, in the response parameters:
https://apidocs.cloudfoundry.org/236/service_instances/creating_a_service_instance.html

If your an administrator (i.e. if you have the basic auth login/passwd for autosleep) you can also access the list of all dashboards by going to `https://YOUR_AUTOSLEEP_URL/admin/debug/` (don't forget last slash)

Cheers

**Comment by gberche-orange** [comment]
@PadmaB 

The dashboard url is displayed by the regular `cf service 'autosleep-service-instance-name'` command

**Comment by arnaudruffin** [comment]
Closed because merged in `feature-wildcard-proxy` branch.
