### ISSUE TITLE
Traffic received while waking up an app returns 500 error status instead of 503

### ISSUE THREAD

**Issue by arnaudruffin** [Orange-OpenSource/autosleep#192]
In current version, when restarting app on incoming traffic we try to handle a transitive "restart in progress" state during which the service returns a 503 error code.

However, we check app state using 

```
cfClient.applicationsV2()
                    .get(GetApplicationRequest.builder()
                            .applicationId(applicationUuid)
                            .build())
                    .get(Config.CF_API_TIMEOUT)
                    .getEntity().getState();
```

This will return _asked state_ and not actual state. (i.e. will return STARTED after a call to `start`, even if the app is still restarting).

**This results in forwarding traffic to an app that is not ready... and so receiving the request again as a wildcard proxy** Fortunately the signature header that we've already added protect us from an infinite loop.

We should have a look on instances states. CF ApplicationInstancesRequest?

**Comment by arnaudruffin** [comment]
@gberche in this case should we wait **for each** instance to be started, or **at least** one?

**Comment by gberche-orange** [comment]
thanks @arnaudruffin 

We'd indeed need to fetch more accurate app state such as with:
- http://apidocs.cloudfoundry.org/236/apps/get_app_summary.html which returns the current state along with the nb of instances
- potentially the V3 API could be more flexible with
  - http://v3-apidocs.cloudfoundry.org/version/release-candidate/index.html#get-a-process
  - http://v3-apidocs.cloudfoundry.org/version/release-candidate/index.html#the-process-stats-object

>  in this case should we wait for each instance to be started, or at least one?

With the wildcard route implementation, as soon as one app instance is up, the wildcard route should not receive traffic anymore for the mapped route, so this should be an edge case.

**Comment by gberche-orange** [comment]
Actually, we'd need to further discuss this as the strategy for HA and scalability for auto-wake-up might instead direct us with autosleep synchronization among autowakeup instances (as to avoid hammering CC API on every incoming autowakeup received traffic)

**Comment by arnaudruffin** [comment]
> http://apidocs.cloudfoundry.org/236/apps/get_app_summary.html which returns the current state along with the nb of instances

I'm not sure `get_app_summary` would be useful, as the `state` return is the same as the app state (=`STARTED` as soon as the start command is launched). The same goes for the `running_instances` field. 

> Actually, we'd need to further discuss this as the strategy for HA and scalability for auto-wake-up might instead direct us with autosleep synchronization among autowakeup instances (as to avoid hammering CC API on every incoming autowakeup received request)

Yes indeed. Too bad we can't rely on route services for now....

**Comment by arnaudruffin** [comment]
This should work if we use ApplicationInstancesRequest in the CF java client and count the instances ...
