### ISSUE TITLE
New release of autosleep

### ISSUE THREAD

**Issue by PadmaB** [Orange-OpenSource/autosleep#198]
Hi,

When is the next release scheduled for autosleep? I am looking for the forced auto-enrollment mode which is fixed few days back. Thanks!

Kind Regards,
Padma

**Comment by gberche-orange** [comment]
Hi @PadmaB

We don't yet have the dates for when we'll be cutting the release, but you can always build from source to benefit from the latest commits in the develop branch. https://github.com/Orange-OpenSource/autosleep/blob/develop/doc/build.md

Let us know if you're lacking some details in the doc.

Mind that we've splitted into two apps, make sure to refresh /rebase your manifest.yml with the one in the repo.
