### ISSUE TITLE
Change the behavior of forced enrollment for service instances

### ISSUE THREAD

**Issue by pradyutsarma** [Orange-OpenSource/autosleep#207]
Currently, the autosleep service does not allow service instances to be deleted if the [forced-autoenrollment](https://github.com/Orange-OpenSource/autosleep#lockauto-enrollment) parameter is set to forced guarded by the secret. A side effect of this is: Org/Space managers who would want to delete a space won’t be able to do it since this service instance won’t be deletable and not all Org/Space managers may have access to the secret parameter (especially in a public PAAS).

However, now that there is this plan of introducing "Automatic scans for orgs/spaces too" via [this feature](https://github.com/Orange-OpenSource/autosleep/issues/201), can we change this behavior of forced enrollment for service instances to the same as it is for binding instances. That is: we allow an user to delete the service instance and if the space is not deleted till the inactivity period, the service instance is created again.

This allows Org/Space managers to delete their owned spaces as and when they would want to. This is a pretty important use case for us.

**Comment by gberche-orange** [comment]
Thanks @pradyutsarma for your feedback. 

The proposed behavior makes sense to me in the context of #201 

I'd prefer to include this feature as part of #201, keep the discussion there, and this issue as duplicate. Any objection ?

**Comment by pradyutsarma** [comment]
Thanks @gberche-orange. No objection at all. That's basically the sole reason why I referred that issue in my comment https://github.com/Orange-OpenSource/autosleep/issues/201#issuecomment-226734488

As you suggested in the other thread, would be a good idea to have a call and discuss the rest of the use cases and workflows.

**Comment by gberche-orange** [comment]
Thanks @pradyutsarma 

Closing this issue for now. Looking forward to receiving your email and having a call with you.
