### ISSUE TITLE
update acceptance documentation

### ISSUE THREAD

**Issue by arnaudruffin** [Orange-OpenSource/autosleep#217]
- main README should point to acceptance.md only, acceptance.md should also point to blob test
- acceptance.md should describe better how to init environment
- for that, we should also include a `requirements.txt`
- pythoncfclient could init itself via cfg file?
- and "cherry on the cake", we should get rid of the pythonpath

**Comment by gberche-orange** [comment]
@antechrestos see comment on https://github.com/Orange-OpenSource/autosleep/pull/220/files#r74086382

Also related to https://github.com/Orange-OpenSource/autosleep/blob/develop/acceptance/acceptance.tmpl.cfg#L3 why is there twice the ``target_endpoint` property (are we assuming two distinct CF CC API endpoints) ?

**Comment by arnaudruffin** [comment]
@gberche-orange regarding `target_endpoint` : they are set in two different sections of the cfg file: _client_ and _autosleep_
The first one will be set with the CF CC API (https://api.nd-cfapi.xxx), the other one is the autosleep service broker endpoint (http://autosleep-arno.cf.ns.xxxxx)

**Comment by antechrestos** [comment]
@arnaudruffin @gberche-orange I added the python version.

**Comment by gberche-orange** [comment]
See more details about virtualenv by benjamin into https://github.com/Orange-OpenSource/autosleep/pull/220/files#r74089164

**Comment by gberche-orange** [comment]
See more details about virtualenv by benjamin into https://github.com/Orange-OpenSource/autosleep/pull/220/files#r74089164

**Comment by gberche-orange** [comment]
See more details about virtualenv by benjamin into https://github.com/Orange-OpenSource/autosleep/pull/220/files#r74089164

**Comment by gberche-orange** [comment]
See more details about virtualenv by benjamin into https://github.com/Orange-OpenSource/autosleep/pull/220/files#r74089164

**Comment by gberche-orange** [comment]
See more details about virtualenv by benjamin into https://github.com/Orange-OpenSource/autosleep/pull/220/files#r74089164
