### ISSUE TITLE
Arbitrary parameters renaming

### ISSUE THREAD

**Issue by arnaudruffin** [Orange-OpenSource/autosleep#84]
Currently we have:
- inactivity
- excludeAppNameRegExp
- no_optout
- secret

My proposals:
- **inactivity :arrow_right: duration**
- **excludeAppNameRegExp :arrow_right: exclude-from-autoscan** 
  (I think we don't need to call it xxx-regexp, as the documentation should be enough to tell that it should contain a regular expression)
- **no_optout :arrow_right: force-rebind**
  Clearer if we decide that "no-optout" means "ok to unbind, but will be re-bound later"
- **secret**

@gberche-orange @antechrestos , feel free to give your points of view.

**Comment by antechrestos** [comment]
- **exclude-from-autoscan** :arrow_right: **exclude-from-autobind**
- **duration** :arrow_right: **idle-duration**

**Comment by gberche-orange** [comment]
Thanks for initiating this. I started drafting specs on the etherpad, I'll need bit more time to be end up with a consistent naming proposal.

**Comment by arnaudruffin** [comment]
**auto-enrollment** : <_standard_ (default) / _forced_> . We could even imagine setting it to "false" to deactivate autobinding.
**exclude-from-auto-enrollment** (default = empty)
**idle-duration** : default = PT24H
**secret** : mandatory when setting **auto-enrollment=forced** or when updating from **forced** to **default**

**Comment by antechrestos** [comment]
@arnaudruffin I agree with you for __auto-enrollment__ implemented as a boolean . I shall do it this way. We may later change it in the parameter reading without touching the code itself.
